// **********************************************************************************
// * Copyright (c) 2013 Robin Murray
// **********************************************************************************
// *
// * File: Token.cs
// *
// * Description:  
// *
// * Author: Robin Murray
// *
// * Generated By: JavaCC: Token.java Version 5.0
// *
// *     JavaCCOptions - TOKEN_EXTENDS=,KEEP_LINE_COL=null,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
// *
// **********************************************************************************
// *
// * Granting License: The MIT License (MIT)
// * 
// *   Permission is hereby granted, free of charge, to any person obtaining a copy
// *   of this software and associated documentation files (the "Software"), to deal
// *   in the Software without restriction, including without limitation the rights
// *   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// *   copies of the Software, and to permit persons to whom the Software is
// *   furnished to do so, subject to the following conditions:
// *   The above copyright notice and this permission notice shall be included in
// *   all copies or substantial portions of the Software.
// *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// *   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// *   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// *   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// *   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// *   THE SOFTWARE.
// * 
// **********************************************************************************

// **********************************************************************************
// * Using
// **********************************************************************************

using System;
using System.Collections.Generic;
using System.Text;

// **********************************************************************************
// * Implementation
// **********************************************************************************

namespace DemiTasse.psrutil
{
    /* Generated By:JavaCC: Do not edit this line. Token.java Version 5.0 */
    /* JavaCCOptions:TOKEN_EXTENDS=,KEEP_LINE_COL=null,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
    /* package irpsr; */

    /**
    * Describes the input token stream.
    */

    public class Token /*: java.io.Serializable*/
    {
        /**
        * The version identifier for this Serializable class.
        * Increment only if the <i>serialized</i> form of the
        * class changes.
        */
        private static readonly long serialVersionUID = 1L;

        /**
        * An integer that describes the kind of this token.  This numbering
        * system is determined by JavaCCParser, and a table of these numbers is
        * stored in the file ...Constants.java.
        */
        //public irParserConstants.RegExpId kind;

        /** The line number of the first character of this Token. */
        public int beginLine;
        
        /** The column number of the first character of this Token. */
        public int beginColumn;
        
        /** The line number of the last character of this Token. */
        public int endLine;
        
        /** The column number of the last character of this Token. */
        public int endColumn;

        /**
        * The string image of the token.
        */
        public string image;

        /**
        * An optional attribute value of the Token.
        * Tokens which are not used as syntactic sugar will often contain
        * meaningful values that will be used later on by the compiler or
        * interpreter. This attribute value is often different from the image.
        * Any subclass of Token that actually wants to return a non-null value can
        * override this method as appropriate.
        */
        public object getValue()
        {
            return null;
        }

        /**
        * No-argument constructor
        */
        public Token()
        {
        }

        /**
        * Returns the image.
        */
        public string toString()
        {
            return image;
        }
    }
    /* JavaCC - OriginalChecksum=95ec07fd565ccea83cc17ac7fe5f1466 (do not edit this line) */
}
